// This file will be auto-generated by Supabase CLI
// Run: supabase gen types typescript --local > src/types/database.ts
// For now, we'll define the types manually

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string | null
          full_name: string | null
          avatar_url: string | null
          default_assumptions: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email?: string | null
          full_name?: string | null
          avatar_url?: string | null
          default_assumptions?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string | null
          full_name?: string | null
          avatar_url?: string | null
          default_assumptions?: Json
          created_at?: string
          updated_at?: string
        }
      }
      properties: {
        Row: {
          id: string
          user_id: string
          name: string
          address: string | null
          city: string | null
          state: string | null
          zip: string | null
          county: string | null
          property_type: string
          beds: number | null
          baths: number | null
          sqft: number | null
          lot_sqft: number | null
          year_built: number | null
          photo_urls: string[]
          notes: string | null
          status: string
          purchase_price: number
          closing_cost_percent: number
          closing_cost_fixed: number
          earnest_money: number
          financing_type: string
          down_payment_percent: number
          down_payment_amount: number | null
          interest_rate: number
          loan_term_years: number
          points: number
          pmi_monthly: number
          rehab_budget_total: number
          rehab_budget_itemized: Json
          rehab_timeline_months: number
          holding_costs_monthly: number
          monthly_rent: number | null
          rent_comps: Json
          vacancy_percent: number
          maintenance_percent: number
          capex_percent: number
          management_percent: number
          insurance_monthly: number
          property_tax_annual: number | null
          property_tax_rate: number | null
          hoa_monthly: number
          utilities_monthly: number
          other_expenses_monthly: number
          arv: number | null
          arv_comps: Json
          refi_ltv_percent: number
          refi_interest_rate: number
          refi_loan_term_years: number
          refi_closing_cost_percent: number
          refi_closing_cost_fixed: number
          appreciation_rate: number
          appreciation_low: number
          appreciation_high: number
          rent_growth_rate: number
          expense_growth_rate: number
          data_sources: Json
          calculated_monthly_cashflow: number | null
          calculated_cap_rate: number | null
          calculated_coc_return: number | null
          calculated_total_investment: number | null
          calculated_cash_left_in_deal: number | null
          created_at: string
          updated_at: string
          analyzed_at: string | null
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          address?: string | null
          city?: string | null
          state?: string | null
          zip?: string | null
          county?: string | null
          property_type?: string
          beds?: number | null
          baths?: number | null
          sqft?: number | null
          lot_sqft?: number | null
          year_built?: number | null
          photo_urls?: string[]
          notes?: string | null
          status?: string
          purchase_price: number
          closing_cost_percent?: number
          closing_cost_fixed?: number
          earnest_money?: number
          financing_type?: string
          down_payment_percent?: number
          down_payment_amount?: number | null
          interest_rate?: number
          loan_term_years?: number
          points?: number
          pmi_monthly?: number
          rehab_budget_total?: number
          rehab_budget_itemized?: Json
          rehab_timeline_months?: number
          holding_costs_monthly?: number
          monthly_rent?: number | null
          rent_comps?: Json
          vacancy_percent?: number
          maintenance_percent?: number
          capex_percent?: number
          management_percent?: number
          insurance_monthly?: number
          property_tax_annual?: number | null
          property_tax_rate?: number | null
          hoa_monthly?: number
          utilities_monthly?: number
          other_expenses_monthly?: number
          arv?: number | null
          arv_comps?: Json
          refi_ltv_percent?: number
          refi_interest_rate?: number
          refi_loan_term_years?: number
          refi_closing_cost_percent?: number
          refi_closing_cost_fixed?: number
          appreciation_rate?: number
          appreciation_low?: number
          appreciation_high?: number
          rent_growth_rate?: number
          expense_growth_rate?: number
          data_sources?: Json
          calculated_monthly_cashflow?: number | null
          calculated_cap_rate?: number | null
          calculated_coc_return?: number | null
          calculated_total_investment?: number | null
          calculated_cash_left_in_deal?: number | null
          created_at?: string
          updated_at?: string
          analyzed_at?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          address?: string | null
          city?: string | null
          state?: string | null
          zip?: string | null
          county?: string | null
          property_type?: string
          beds?: number | null
          baths?: number | null
          sqft?: number | null
          lot_sqft?: number | null
          year_built?: number | null
          photo_urls?: string[]
          notes?: string | null
          status?: string
          purchase_price?: number
          closing_cost_percent?: number
          closing_cost_fixed?: number
          earnest_money?: number
          financing_type?: string
          down_payment_percent?: number
          down_payment_amount?: number | null
          interest_rate?: number
          loan_term_years?: number
          points?: number
          pmi_monthly?: number
          rehab_budget_total?: number
          rehab_budget_itemized?: Json
          rehab_timeline_months?: number
          holding_costs_monthly?: number
          monthly_rent?: number | null
          rent_comps?: Json
          vacancy_percent?: number
          maintenance_percent?: number
          capex_percent?: number
          management_percent?: number
          insurance_monthly?: number
          property_tax_annual?: number | null
          property_tax_rate?: number | null
          hoa_monthly?: number
          utilities_monthly?: number
          other_expenses_monthly?: number
          arv?: number | null
          arv_comps?: Json
          refi_ltv_percent?: number
          refi_interest_rate?: number
          refi_loan_term_years?: number
          refi_closing_cost_percent?: number
          refi_closing_cost_fixed?: number
          appreciation_rate?: number
          appreciation_low?: number
          appreciation_high?: number
          rent_growth_rate?: number
          expense_growth_rate?: number
          data_sources?: Json
          calculated_monthly_cashflow?: number | null
          calculated_cap_rate?: number | null
          calculated_coc_return?: number | null
          calculated_total_investment?: number | null
          calculated_cash_left_in_deal?: number | null
          created_at?: string
          updated_at?: string
          analyzed_at?: string | null
        }
      }
      scenarios: {
        Row: {
          id: string
          user_id: string
          property_id: string
          name: string
          description: string | null
          assumptions_override: Json
          projections_10yr: Json
          summary_metrics: Json
          is_default: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          property_id: string
          name: string
          description?: string | null
          assumptions_override?: Json
          projections_10yr?: Json
          summary_metrics?: Json
          is_default?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          property_id?: string
          name?: string
          description?: string | null
          assumptions_override?: Json
          projections_10yr?: Json
          summary_metrics?: Json
          is_default?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      markets: {
        Row: {
          id: string
          zip: string | null
          city: string | null
          county: string | null
          state: string | null
          metro_area: string | null
          median_home_price: number | null
          median_rent: number | null
          rent_price_ratio: number | null
          price_per_sqft: number | null
          rent_per_sqft: number | null
          appreciation_1yr: number | null
          appreciation_3yr_cagr: number | null
          appreciation_5yr_cagr: number | null
          appreciation_10yr_cagr: number | null
          population: number | null
          population_growth_1yr: number | null
          population_growth_5yr: number | null
          median_household_income: number | null
          income_growth_1yr: number | null
          unemployment_rate: number | null
          job_growth_1yr: number | null
          months_of_inventory: number | null
          days_on_market_avg: number | null
          new_listings_yoy_change: number | null
          building_permits_yoy_change: number | null
          overall_grade: string | null
          cashflow_score: number | null
          appreciation_score: number | null
          stability_score: number | null
          data_date: string | null
          sources: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          zip?: string | null
          city?: string | null
          county?: string | null
          state?: string | null
          metro_area?: string | null
          median_home_price?: number | null
          median_rent?: number | null
          rent_price_ratio?: number | null
          price_per_sqft?: number | null
          rent_per_sqft?: number | null
          appreciation_1yr?: number | null
          appreciation_3yr_cagr?: number | null
          appreciation_5yr_cagr?: number | null
          appreciation_10yr_cagr?: number | null
          population?: number | null
          population_growth_1yr?: number | null
          population_growth_5yr?: number | null
          median_household_income?: number | null
          income_growth_1yr?: number | null
          unemployment_rate?: number | null
          job_growth_1yr?: number | null
          months_of_inventory?: number | null
          days_on_market_avg?: number | null
          new_listings_yoy_change?: number | null
          building_permits_yoy_change?: number | null
          overall_grade?: string | null
          cashflow_score?: number | null
          appreciation_score?: number | null
          stability_score?: number | null
          data_date?: string | null
          sources?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          zip?: string | null
          city?: string | null
          county?: string | null
          state?: string | null
          metro_area?: string | null
          median_home_price?: number | null
          median_rent?: number | null
          rent_price_ratio?: number | null
          price_per_sqft?: number | null
          rent_per_sqft?: number | null
          appreciation_1yr?: number | null
          appreciation_3yr_cagr?: number | null
          appreciation_5yr_cagr?: number | null
          appreciation_10yr_cagr?: number | null
          population?: number | null
          population_growth_1yr?: number | null
          population_growth_5yr?: number | null
          median_household_income?: number | null
          income_growth_1yr?: number | null
          unemployment_rate?: number | null
          job_growth_1yr?: number | null
          months_of_inventory?: number | null
          days_on_market_avg?: number | null
          new_listings_yoy_change?: number | null
          building_permits_yoy_change?: number | null
          overall_grade?: string | null
          cashflow_score?: number | null
          appreciation_score?: number | null
          stability_score?: number | null
          data_date?: string | null
          sources?: Json
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
